apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      version: 4.1.10 # https://artifacthub.io/packages/helm/bitnami/metallb