apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      FLUX_CONFIG_PATH: ./clusters/production
      ZONE: production # production
      ENVIRONMENT: prod # prod
      ACTIVE_CLUSTER: kubernetes
      CERT_MANAGER_VERSION: 1.10.0 # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    substituteFrom:
    - kind: ConfigMap
      name: tumogroup-flux-config
