apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: default
spec:
  chart:
    spec:
      version: 3.8.2 # https://artifacthub.io/packages/helm/metrics-server/metrics-server