apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3

